package com.fidoarp.catalog.model.impl;

import com.fidoarp.catalog.model.App;
import com.fidoarp.catalog.service.AppLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the App service. Represents a row in the &quot;fido_app&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppImpl
 * @see com.fidoarp.catalog.model.App
 * @generated
 */
public abstract class AppBaseImpl extends AppModelImpl implements App {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a app model instance should use the {@link App} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            AppLocalServiceUtil.addApp(this);
        } else {
            AppLocalServiceUtil.updateApp(this);
        }
    }
}
