package com.fidoarp.catalog.model.impl;

import com.fidoarp.catalog.model.AppStatus;
import com.fidoarp.catalog.service.AppStatusLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the AppStatus service. Represents a row in the &quot;fido_app_status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppStatusImpl
 * @see com.fidoarp.catalog.model.AppStatus
 * @generated
 */
public abstract class AppStatusBaseImpl extends AppStatusModelImpl
    implements AppStatus {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a app status model instance should use the {@link AppStatus} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            AppStatusLocalServiceUtil.addAppStatus(this);
        } else {
            AppStatusLocalServiceUtil.updateAppStatus(this);
        }
    }
}
