package com.fidoarp.catalog.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the ProductType service. Represents a row in the &quot;fido_product_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fidoarp.catalog.model.impl.ProductTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fidoarp.catalog.model.impl.ProductTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductType
 * @see com.fidoarp.catalog.model.impl.ProductTypeImpl
 * @see com.fidoarp.catalog.model.impl.ProductTypeModelImpl
 * @generated
 */
public interface ProductTypeModel extends BaseModel<ProductType> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a product type model instance should use the {@link ProductType} interface instead.
     */

    /**
     * Returns the primary key of this product type.
     *
     * @return the primary key of this product type
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this product type.
     *
     * @param primaryKey the primary key of this product type
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the product type ID of this product type.
     *
     * @return the product type ID of this product type
     */
    public long getProductTypeId();

    /**
     * Sets the product type ID of this product type.
     *
     * @param productTypeId the product type ID of this product type
     */
    public void setProductTypeId(long productTypeId);

    /**
     * Returns the product type code of this product type.
     *
     * @return the product type code of this product type
     */
    @AutoEscape
    public String getProductTypeCode();

    /**
     * Sets the product type code of this product type.
     *
     * @param productTypeCode the product type code of this product type
     */
    public void setProductTypeCode(String productTypeCode);

    /**
     * Returns the name of this product type.
     *
     * @return the name of this product type
     */
    public String getName();

    /**
     * Returns the localized name of this product type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized name of this product type
     */
    @AutoEscape
    public String getName(Locale locale);

    /**
     * Returns the localized name of this product type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this product type. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getName(Locale locale, boolean useDefault);

    /**
     * Returns the localized name of this product type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized name of this product type
     */
    @AutoEscape
    public String getName(String languageId);

    /**
     * Returns the localized name of this product type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this product type
     */
    @AutoEscape
    public String getName(String languageId, boolean useDefault);

    @AutoEscape
    public String getNameCurrentLanguageId();

    @AutoEscape
    public String getNameCurrentValue();

    /**
     * Returns a map of the locales and localized names of this product type.
     *
     * @return the locales and localized names of this product type
     */
    public Map<Locale, String> getNameMap();

    /**
     * Sets the name of this product type.
     *
     * @param name the name of this product type
     */
    public void setName(String name);

    /**
     * Sets the localized name of this product type in the language.
     *
     * @param name the localized name of this product type
     * @param locale the locale of the language
     */
    public void setName(String name, Locale locale);

    /**
     * Sets the localized name of this product type in the language, and sets the default locale.
     *
     * @param name the localized name of this product type
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setName(String name, Locale locale, Locale defaultLocale);

    public void setNameCurrentLanguageId(String languageId);

    /**
     * Sets the localized names of this product type from the map of locales and localized names.
     *
     * @param nameMap the locales and localized names of this product type
     */
    public void setNameMap(Map<Locale, String> nameMap);

    /**
     * Sets the localized names of this product type from the map of locales and localized names, and sets the default locale.
     *
     * @param nameMap the locales and localized names of this product type
     * @param defaultLocale the default locale
     */
    public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

    /**
     * Returns the description of this product type.
     *
     * @return the description of this product type
     */
    public String getDescription();

    /**
     * Returns the localized description of this product type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized description of this product type
     */
    @AutoEscape
    public String getDescription(Locale locale);

    /**
     * Returns the localized description of this product type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized description of this product type. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getDescription(Locale locale, boolean useDefault);

    /**
     * Returns the localized description of this product type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized description of this product type
     */
    @AutoEscape
    public String getDescription(String languageId);

    /**
     * Returns the localized description of this product type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized description of this product type
     */
    @AutoEscape
    public String getDescription(String languageId, boolean useDefault);

    @AutoEscape
    public String getDescriptionCurrentLanguageId();

    @AutoEscape
    public String getDescriptionCurrentValue();

    /**
     * Returns a map of the locales and localized descriptions of this product type.
     *
     * @return the locales and localized descriptions of this product type
     */
    public Map<Locale, String> getDescriptionMap();

    /**
     * Sets the description of this product type.
     *
     * @param description the description of this product type
     */
    public void setDescription(String description);

    /**
     * Sets the localized description of this product type in the language.
     *
     * @param description the localized description of this product type
     * @param locale the locale of the language
     */
    public void setDescription(String description, Locale locale);

    /**
     * Sets the localized description of this product type in the language, and sets the default locale.
     *
     * @param description the localized description of this product type
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setDescription(String description, Locale locale,
        Locale defaultLocale);

    public void setDescriptionCurrentLanguageId(String languageId);

    /**
     * Sets the localized descriptions of this product type from the map of locales and localized descriptions.
     *
     * @param descriptionMap the locales and localized descriptions of this product type
     */
    public void setDescriptionMap(Map<Locale, String> descriptionMap);

    /**
     * Sets the localized descriptions of this product type from the map of locales and localized descriptions, and sets the default locale.
     *
     * @param descriptionMap the locales and localized descriptions of this product type
     * @param defaultLocale the default locale
     */
    public void setDescriptionMap(Map<Locale, String> descriptionMap,
        Locale defaultLocale);

    /**
     * Returns the status of this product type.
     *
     * @return the status of this product type
     */
    public boolean getStatus();

    /**
     * Returns <code>true</code> if this product type is status.
     *
     * @return <code>true</code> if this product type is status; <code>false</code> otherwise
     */
    public boolean isStatus();

    /**
     * Sets whether this product type is status.
     *
     * @param status the status of this product type
     */
    public void setStatus(boolean status);

    /**
     * Returns the organization ID of this product type.
     *
     * @return the organization ID of this product type
     */
    public long getOrganizationId();

    /**
     * Sets the organization ID of this product type.
     *
     * @param organizationId the organization ID of this product type
     */
    public void setOrganizationId(long organizationId);

    /**
     * Returns the template ID of this product type.
     *
     * @return the template ID of this product type
     */
    public long getTemplateId();

    /**
     * Sets the template ID of this product type.
     *
     * @param templateId the template ID of this product type
     */
    public void setTemplateId(long templateId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException;

    public Object clone();

    public int compareTo(ProductType productType);

    public int hashCode();

    public CacheModel<ProductType> toCacheModel();

    public ProductType toEscapedModel();

    public ProductType toUnescapedModel();

    public String toString();

    public String toXmlString();
}
